service: localstack-websockets

provider:
  name: aws
  deploymentBucket:
    name: localstack-websockets-serverless
  stackTags:
    aws-apn-id: pc:9yq38ki5jw5mas7jhjthpgveo

package:
  patterns:
    - "!.venv/**"

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

custom:
  localstack:
    stages: [local]

functions:
  connectionHandler:
    handler: handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: handler.handler
    events:
      - websocket:
          route: $default
          routeResponseSelectionExpression: $default
  actionHandler:
    handler: handler.handler
    events:
      - websocket:
          route: test-action
          routeResponseSelectionExpression: $default
