name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install LocalStack
      run:  pip install localstack awscli-local[ver1]
    
    - name: Pull the latest docker image
      run: docker pull localstack/localstack
    
    - name: Execute tests
      env:
        LOCALSTACK_API_KEY: ${{ secrets.TEST_LOCALSTACK_API_KEY }}
        DNS_ADDRESS: 127.0.0.1
      run: make test-ci-all
