name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install LocalStack
      run:
          # install LocalStack cli and awslocal
          pip install localstack awscli-local[ver1]
          # Make sure to pull the latest version of the image
          docker pull localstack/localstack
    - name: Execute tests
      env:
        LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
      run: make test-ci-all
